version: "3"
services:
  frontend:
    image: gyungku/topster-front

  nginx:
    restart: always
    image: gyungku/topster-nginx
    ports:
      - "80:80"

  backend:
    image: gyungku/topster-backend
#    environment:
#      MYSQL_HOST: $MYSQL_HOST
#      MYSQL_USER: $MYSQL_USER
#      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
#      MYSQL_DATABASE: $MYSQL_DATABASE
#      MYSQL_PORT: $MYSQL_PORT
    depends_on:
      - redis
#      - mysql
    env_file:
      - .env

  redis:
    image: gyungku/topster-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    container_name: redis

#  mysql:
#    container_name: mysql
#    image: gyungku/topster-mysql
#    restart: unless-stopped
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./mysql/mysql_data:/var/lib/mysql
#      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
#    environment:
#      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
#      MYSQL_DATABASE: ${MYSQL_DATABASE}